# Generated by Django 5.0.1 on 2024-01-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullNameCyrillic', models.CharField(max_length=100)),
                ('fullNameLatin', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('issueDate', models.DateField()),
                ('expiryDate', models.DateField()),
                ('nationalId', models.CharField(max_length=255)),
                ('passportNumber', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('maritalStatus', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced')], max_length=20)),
                ('rma', models.IntegerField()),
                ('jobLocation', models.CharField(max_length=255)),
                ('photo3x4', models.ImageField(upload_to='3x4/')),
                ('idPhoto', models.ImageField(upload_to='passport/')),
                ('idWithPhoto', models.ImageField(upload_to='selfie/')),
            ],
        ),
    ]
