# Generated by Django 5.0.1 on 2024-01-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='phoneNumber',
            field=models.CharField(default=555555, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formdata',
            name='idPhoto',
            field=models.ImageField(upload_to='passport'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='idWithPhoto',
            field=models.ImageField(upload_to='selfie'),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='photo3x4',
            field=models.ImageField(upload_to='3x4'),
        ),
    ]
