# Generated by Django 5.0.1 on 2024-01-12 19:13

import django.utils.timezone
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_formdata_phonenumber_alter_formdata_idphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='department',
            field=models.CharField(choices=[('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Бакалавриат'), ('Аспирантура', 'Бакалавриат'), ('Доктарантура', 'Бакалавриат')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formdata',
            name='eduType',
            field=models.CharField(choices=[('Рӯзона', 'Рӯзона'), ('Шабона', 'Шабона')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formdata',
            name='studentCard',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formdata',
            name='idPhoto',
            field=models.ImageField(upload_to=myapp.models.custom_front_id_photo_filename),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='idWithPhoto',
            field=models.ImageField(upload_to=myapp.models.custom_id_with_photo_filename),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='photo3x4',
            field=models.ImageField(upload_to=myapp.models.custom_photo_filename),
        ),
    ]
