# Generated by Django 5.0.1 on 2024-01-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_formdata_department_formdata_edutype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='maritalStatus',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='nationalId',
        ),
    ]
