# Generated by Django 5.0.1 on 2024-01-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_formdata_maritalstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='jobLocation',
            field=models.BooleanField(default=True),
        ),
    ]
