# Generated by Django 5.0.1 on 2024-01-25 20:30

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_idphoto_formdata_idphotofront_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='comapny',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formdata',
            name='school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formdata',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formdata',
            name='userType',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formdata',
            name='department',
            field=models.CharField(blank=True, choices=[('факултети идоракунии давлат', 'факултети идоракунии давлат'), ('факултети хукукшиноси', 'факултети хукукшиноси'), ('факултети дипломатия ва сиёсат', 'факултети дипломатия ва сиёсат'), ('факултети тахсилоти фосилави ва тахсилоти дуюми олии касби', 'факултети тахсилоти фосилави ва тахсилоти дуюми олии касби'), ('шуъбаи магистратура', 'шуъбаи магистратура'), ('магистратураи "мактаби давлатдории Эмомали Рахмон"', 'магистратураи "мактаби давлатдории Эмомали Рахмон"'), ('шуъбаи омодакунии кадрхои илми ва илми-педагоги', 'шуъбаи омодакунии кадрхои илми ва илми-педагоги')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='eduType',
            field=models.CharField(blank=True, choices=[('Рӯзона', 'Рӯзона'), ('Ғоибона', 'Ғоибона')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='photo3x4',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.custom_photo_filename),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='studentCard',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
