# Generated by Django 5.0.1 on 2024-01-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_formdata_comapny_formdata_school_formdata_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='region',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
