# Generated by Django 5.0.1 on 2024-05-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_formdata_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='comapny',
            new_name='company',
        ),
    ]
